import Navbar from "@/components/ui/navigation/Navbar";
import "./globals.css";

export const metadata = {
  title: "Portfolio-V2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-my_black text-my_white_30 font-MonoLisa">
        <Navbar />
        <main className="max-w-screen-lg mx-auto py-20 text-sm">
          {children}
        </main>
      </body>
    </html>
  );
}
