"use client";
import Navbar from "@/components/ui/navigation/Navbar";
import "./globals.css";
import { useEffect } from "react";

export const metadata = {
  title: "Portfolio-V2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  useEffect(() => {
    // Disable right-click
    window.addEventListener("contextmenu", function (e) {
      e.preventDefault();
    });

    // Disable Ctrl+C (or Cmd+C on Mac)
    window.addEventListener("keydown", function (e) {
      if ((e.ctrlKey || e.metaKey) && e.key === "c") {
        e.preventDefault();
      }
    });

    // Cleanup event listeners on unmount (optional)
    return () => {
      window.removeEventListener("contextmenu", function (e) {
        e.preventDefault();
      });
      window.removeEventListener("keydown", function (e) {
        if ((e.ctrlKey || e.metaKey) && e.key === "c") {
          e.preventDefault();
        }
      });
    };
  }, []);
  return (
    <html lang="en">
      <body className="bg-black_01 text-white_02 font-JetBrains">
        <Navbar />
        <main className="max-w-screen-lg mx-auto py-20  text-sm px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
